name: Deploy to Hostinger

on:
  push:
    branches:
      - main   # change if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

    - name: Deploy to Hostinger
      run: |
        ssh -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} "cd /home/${{ secrets.HOSTINGER_USER }}/domains/qonkar.com/public_html && git pull origin main"